/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StoriesTopImport } from './routes/stories.top'
import { Route as StoriesNewImport } from './routes/stories.new'
import { Route as StoriesBestImport } from './routes/stories.best'
import { Route as ItemIdImport } from './routes/item.$id'

// Create/Update Routes

const StoriesTopRoute = StoriesTopImport.update({
  path: '/stories/top',
  getParentRoute: () => rootRoute,
} as any)

const StoriesNewRoute = StoriesNewImport.update({
  path: '/stories/new',
  getParentRoute: () => rootRoute,
} as any)

const StoriesBestRoute = StoriesBestImport.update({
  path: '/stories/best',
  getParentRoute: () => rootRoute,
} as any)

const ItemIdRoute = ItemIdImport.update({
  path: '/item/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/item/$id': {
      preLoaderRoute: typeof ItemIdImport
      parentRoute: typeof rootRoute
    }
    '/stories/best': {
      preLoaderRoute: typeof StoriesBestImport
      parentRoute: typeof rootRoute
    }
    '/stories/new': {
      preLoaderRoute: typeof StoriesNewImport
      parentRoute: typeof rootRoute
    }
    '/stories/top': {
      preLoaderRoute: typeof StoriesTopImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  ItemIdRoute,
  StoriesBestRoute,
  StoriesNewRoute,
  StoriesTopRoute,
])

/* prettier-ignore-end */
